In [68]:
import pandas as pd
import numpy as np
import sys
import os
from os import system
import csv
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB

In [13]:
data_dir = "data"
for root, dirs, files in os.walk(data_dir, topdown=False):
    for name in files:
        print(os.path.join(root, name))
    for name in dirs:
        print(os.path.join(root, name))

data/title.basics.tsv/data.tsv
data/data-sarc-sample/sarc/sarcastic_879.txt
data/data-sarc-sample/sarc/sarcastic_223.txt
data/data-sarc-sample/sarc/sarcastic_318.txt
data/data-sarc-sample/sarc/sarcastic_118.txt
data/data-sarc-sample/sarc/sarcastic_932.txt
data/data-sarc-sample/sarc/sarcastic_129.txt
data/data-sarc-sample/sarc/sarcastic_494.txt
data/data-sarc-sample/sarc/sarcastic_662.txt
data/data-sarc-sample/sarc/sarcastic_592.txt
data/data-sarc-sample/sarc/sarcastic_135.txt
data/data-sarc-sample/sarc/sarcastic_470.txt
data/data-sarc-sample/sarc/sarcastic_87.txt
data/data-sarc-sample/sarc/sarcastic_209.txt
data/data-sarc-sample/sarc/sarcastic_869.txt
data/data-sarc-sample/sarc/sarcastic_743.txt
data/data-sarc-sample/sarc/sarcastic_952.txt
data/data-sarc-sample/sarc/sarcastic_933.txt
data/data-sarc-sample/sarc/sarcastic_904.txt
data/data-sarc-sample/sarc/sarcastic_230.txt
data/data-sarc-sample/sarc/sarcastic_784.txt
data/data-sarc-sample/sarc/sarcastic_915.txt
data/data-sarc-sample/sar

In [14]:
# Combine to TSV
if 'data' not in os.getcwd(): 
    os.chdir("data")
system("pwd")
if not os.path.exists('combined.csv'):
    system("cat *.csv > combined.csv")
os.chdir("../")

/home/pavle/Documents/Git/medvidov/dsci550/data


In [15]:
pix_df = pd.read_csv("data/combined.csv")
pix_df.head()

Story Primary ID       Story ID User Primary ID        User ID  Gender Age  \
0           105133  STY1654473727            8255  USR1628503147  others  13   
1           105132  STY1654473498            8601  USR1630424770  others  13   
2           105131  STY1654473332           28647  USR1646131566     NaN  12   
3           105130  STY1654472717           40917  USR1654101217    male  23   
4           105129  STY1654472629           30966  USR1649551870     NaN  12   

                                               Title  \
0           2. Looking back : On the bench once more   
1  3. Contemporary Afghanistan : The 'Bonn Agreem...   
2  20. A Question of Pride : The 'Chushi Gangdrug...   
3  From Undesirable to Undeniable - The Cody Rhod...   
4  Aboriginal elders voice concerns over proposed...   

                                           Narrative  \
0  On the Bench Once More continues....\n\nWhile ...   
1  International Community in\nAfghanistan contin...   
2  Enter the Dragon: Chinese Invasion \nof Tibet ...   
3  WRESTLING HAS MORE THAN ONE ROYAL FAMILY!! \n\...   
4  It is far too soon to be talking about a propo...   

                                               Media Account Created Date  \
0  https://image.pixstory.com/Pixstory-image-1628...  2021-08-09 15:29:07   
1  https://image.pixstory.com/Pixstory-image-1630...  2021-08-31 21:16:10   
2  https://image.pixstory.com/Pixstory-image-1646...  2022-03-01 16:16:06   
3  https://image.pixstory.com/Pixstory-image-1654...  2022-06-01 22:03:37   
4  https://image.pixstory.com/Pixstory-image-1654...  2022-04-10 06:21:10   

                                            Interest  
0                                looking back, books  
1                    contemporary afghanistan, books  
2                         a question of pride, books  
3                cody rhodes, wwe, seth rollins, aew  
4  aboriginal, indigenous people, indigenous righ...

In [45]:
# Sarcasm classification using corpus V2
# https://thecleverprogrammer.com/2021/08/24/sarcasm-detection-with-machine-learning/

sarc_data_dir = "data/sarcasm_v2/"

sarc_df = pd.DataFrame()

for root, dirs, files in os.walk(sarc_data_dir, topdown=False):
    for name in files:
        # print(os.path.join(root, name))
        df = pd.read_csv(os.path.join(root, name))
        # print(df.shape)
        sarc_df = pd.concat([sarc_df, df])
    for name in dirs:
        # print(os.path.join(root, name))
        pass

sarc_df.groupby('class')
sarc_df = sarc_df.replace('notsarc',0)
sarc_df = sarc_df.replace('sarc',1)
sarc_df

class    id                                               text
0         0     1  Archie, the ONLY issue that gays don't have a ...
1         0     2  No, not really. All that is different is the n...
2         0     3  It's ashame that everyone keeps looking for th...
3         0     4  Almost? Usually, that is true, and it involves...
4         0     5  And so have animals. Plants have been wiped ou...
...     ...   ...                                                ...
6515      1  6516  depends on when the baby bird died.   run alon...
6516      1  6517  ok, sheesh, to clarify, women who arent aborti...
6517      1  6518  so..   eh??   hows this sound?   will it fly w...
6518      1  6519  I think we should put to a vote, the right of ...
6519      1  6520  You have a blob of tissue in your "but(sic)"? ...

[9386 rows x 3 columns]

In [70]:
x = np.array(sarc_df["text"])
y = np.array(sarc_df["class"])

cv = CountVectorizer()

X = cv.fit_transform(x) # Fit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify = y)

bern = BernoulliNB()
bern.fit(X_train, y_train)
mult = MultinomialNB()
mult.fit(X_train, y_train)
print(bern.score(X_test, y_test))
print(mult.score(X_test, y_test))

0.6970181043663471
0.7374866879659212


In [88]:
sarcasm = []
j = 0
for i in pix_df.iterrows():
    text = [np.str_(i[1]['Narrative'])]
    data = cv.transform(text)
    output = mult.predict(data)
    sarcasm.append(output)
    j += 1
    if j == 100:
        break
sarcasm

[array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),